package Lesson8.Assignments.studentbrowser;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iyan5440
 */
public class StudentBrowser extends javax.swing.JFrame {

    Student s[];
    int size, curstu;
    public StudentBrowser() {
        initComponents();
        s = new Student[10];
        size=0;
        curstu=-1;
        fillData();
        showStudent();
    }
    
    private void fillData(){
        String name[] = {"Bart Simpson","Chief Whiggum","Edna Crabapple","Moe Sizzleback","Barney Gumble"};
        int marks[][] ={
            {58,65,52},{71,81,66},{85,86,95},{41,52,25},{71,72,81}
        };
        for (int i = 0; i < name.length; i++) {
            //student now requires a name and an array of 3 marks
            //each item in the marks array is an array of 3 marks
            s[i] = new Student(name[i],marks[i]);
            size++;
            
            //this line is just to verify that you have students, it can be commented out later:
            //System.out.println(s[i].getName() + "\t Average " + s[i].getAvg());
        }
        
        //lets start on the first student
        curstu=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        btnnxt = new javax.swing.JButton();
        btnbac = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        lblcount = new javax.swing.JLabel();
        lblindex = new javax.swing.JLabel();
        txtt1 = new javax.swing.JTextField();
        txtt2 = new javax.swing.JTextField();
        txtt3 = new javax.swing.JTextField();
        txtavg = new javax.swing.JTextField();
        lblname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Test 1:");

        jLabel3.setText("Test 2:");

        jLabel4.setText("Test 3:");

        jLabel5.setText("Average:");

        jLabel6.setText("Count:");

        jLabel7.setText("Current Index:");

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnmod.setText("MODIFY");
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });

        btnlast.setText(">>");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        btnnxt.setText(">");
        btnnxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnxtActionPerformed(evt);
            }
        });

        btnbac.setText("<");
        btnbac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacActionPerformed(evt);
            }
        });

        btnfirst.setText("<<");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        lblcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcount.setText("...");
        lblcount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblcount.setOpaque(true);

        lblindex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblindex.setText("...");
        lblindex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblindex.setOpaque(true);

        txtt1.setEditable(false);
        txtt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtt1ActionPerformed(evt);
            }
        });

        txtt2.setEditable(false);
        txtt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtt2ActionPerformed(evt);
            }
        });

        txtt3.setEditable(false);
        txtt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtt3ActionPerformed(evt);
            }
        });

        txtavg.setEditable(false);
        txtavg.setBackground(new java.awt.Color(0, 0, 0));
        txtavg.setForeground(new java.awt.Color(255, 255, 255));
        txtavg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtavg.setText("...");
        txtavg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtavg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtavgActionPerformed(evt);
            }
        });

        lblname.setEditable(false);
        lblname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblindex, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtt1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(txtt2)
                                    .addComponent(txtt3)
                                    .addComponent(txtavg))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnfirst)
                                .addGap(32, 32, 32)
                                .addComponent(btnbac)
                                .addGap(45, 45, 45)
                                .addComponent(btnnxt)
                                .addGap(49, 49, 49)
                                .addComponent(btnlast)
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnadd)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnmod)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnadd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnmod)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtavg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfirst)
                    .addComponent(btnbac)
                    .addComponent(btnnxt)
                    .addComponent(btnlast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lblcount)
                    .addComponent(lblindex))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showStudent(){
        lblname.setText(s[curstu].getName());
        txtt1.setText(""+s[curstu].getMark(0));
        txtt2.setText(""+s[curstu].getMark(1));
        txtt3.setText(""+s[curstu].getMark(2));
        txtavg.setText("" +s[curstu].getAvg());
        lblcount.setText("" +size);
        lblindex.setText("" +(curstu+1));
        
    }
    
    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
        curstu=0;
        showStudent();
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnbacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacActionPerformed
        if(curstu > 0){
            curstu--;
            showStudent();
        }
    }//GEN-LAST:event_btnbacActionPerformed

    private void btnnxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnxtActionPerformed
        if(curstu<size-1 && curstu>-1){
            curstu++;
            showStudent();
        }
    }//GEN-LAST:event_btnnxtActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        curstu=size-1;
        System.out.println(curstu);
        System.out.println(size);
        showStudent();
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        StudentPopup form = new StudentPopup(this,true);
        form.setForm(s[curstu]);
        form.setModal(true);
        form.setLocationRelativeTo(this); //popup right over the form
        form.setVisible(true);
        Student temp = form.getStudent();
        
        String em = temp.vaildateData();
        if(em==null){
            s[curstu]=temp;
            showStudent();
        }
        else{
            JOptionPane.showMessageDialog(this,em);
        }
    }//GEN-LAST:event_btnmodActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if(size<10){
            StudentPopup form = new StudentPopup(this,true);
            form.setModal(true);
            form.setLocationRelativeTo(this); //popup right over the form
            form.setVisible(true);
            //after dispose this code will resume here...
            Student temp = form.getStudent();

            String em = temp.vaildateData();
            if(em==null){
                s[size]=temp;
                curstu=size;
                size++;
                showStudent();
            }
            else{
                JOptionPane.showMessageDialog(this,em);
            }
        }
        if(size>=10){
            
        }
        
        //System.out.println("This prints after form is dismissed");
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtt1ActionPerformed

    private void txtt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtt2ActionPerformed

    private void txtt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtt3ActionPerformed

    private void txtavgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtavgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtavgActionPerformed

    private void lblnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentBrowser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbac;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnnxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblcount;
    private javax.swing.JLabel lblindex;
    private javax.swing.JTextField lblname;
    private javax.swing.JTextField txtavg;
    private javax.swing.JTextField txtt1;
    private javax.swing.JTextField txtt2;
    private javax.swing.JTextField txtt3;
    // End of variables declaration//GEN-END:variables
}
